PULL_REQUEST_TEMPLATE:
  branches:
    dev:
      template: PULL_REQUEST_TEMPLATE/dev.md
    staging:
      template: PULL_REQUEST_TEMPLATE/staging.md
    production:
      template: PULL_REQUEST_TEMPLATE/production.md
  

