name: CI/CD Pipeline

on:
 
  pull_request:
    branches:
      - dev
      - staging
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

   
      

  

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to environment
      run: |
        if [ "${{ github.ref }}" == "refs/heads/feature" ]; then
          echo "Deploying to Feature Environment"
          # Add deployment commands for feature environment
        elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
          echo "Deploying to Dev Environment"
          # Add deployment commands for dev environment
        elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
          echo "Deploying to Staging Environment"
          # Add deployment commands for staging environment
        elif [ "${{ github.ref }}" == "refs/heads/production" ]; then
          echo "Deploying to Production Environment"
          # Add deployment commands for production environment
        fi
